---
- name: Config safe SSH
  ansible.builtin.template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config.d/00-hardening.conf
    owner: root
    group: root
    mode: '0600'
    validate: /usr/sbin/sshd -t -f %s
  notify: Restart sshd

- name: Force handlers
  ansible.builtin.meta: flush_handlers

- name: Wait for connection
  ansible.builtin.wait_for_connection:
    delay: 3
    timeout: 25
